development:
  adapter: mysql2
  encoding: utf8
  database: prelaunchr_development
  pool: 125
  username: root
  password:
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  database: prelaunchr_test
  pool: 125
  username: root
  password:
  host: localhost
